In [1]:
import numpy as np
from scipy.sparse import csr_matrix

A = np.array([
    [1,0,0,1,0,0],
    [0,0,2,0,0,1],
    [0,0,0,2,0,3],
])

print(A)

S = csr_matrix(A)
print(S)
print(type(S))

B = S.todense()
print(B)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 3]]
  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2
  (2, 5)	3
<class 'scipy.sparse.csr.csr_matrix'>
[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 3]]


In [2]:
A = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1],
])

print(A)

S = csr_matrix(A)
print(S)
print(type(S))

B = S.todense()
print(B)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
  (0, 0)	1
  (1, 1)	1
  (2, 2)	1
<class 'scipy.sparse.csr.csr_matrix'>
[[1 0 0]
 [0 1 0]
 [0 0 1]]
